// Executable, subcommand and wrapper tables the bash capability analyzer classifies commands against.

export const INTERPRETERS = new Set([
  "sh",
  "bash",
  "zsh",
  "dash",
  "ksh",
  "ash",
  "mksh",
  "fish",
  "python",
  "python2",
  "python3",
  "py",
  "node",
  "nodejs",
  "bun",
  "deno",
  "tsx",
  "ruby",
  "rb",
  "perl",
  "php",
  "lua",
  "tclsh",
  "wish",
  "java",
  "javac",
  "dotnet",
  "Rscript",
  "julia",
  "awk",
  "gawk",
  "nawk",
]);

export const TEST_RUNNERS = new Set([
  "pytest",
  "py.test",
  "unittest",
  "jest",
  "vitest",
  "mocha",
  "ava",
  "karma",
  "jasmine",
  "cypress",
  "playwright",
  "nx",
  "rake",
  "rspec",
  "minitest",
  "go", // `go test`
  "cargo", // `cargo test`
  "gradle", // `gradle test`
  "mvn", // `mvn test`
  "make", // often runs a test target
  "cmake",
  "ctest",
  "tap",
  "tape",
  "nu",
]);

export const PACKAGE_MANAGERS = new Set([
  "npm",
  "pnpm",
  "yarn",
  "bun", // also an interpreter; dual-classified below
  "pip",
  "pip3",
  "pipx",
  "poetry",
  "uv",
  "conda",
  "mamba",
  "gem",
  "bundle",
  "cargo",
  "go", // `go get` / `go install`
  "composer",
  "mvn",
  "gradle",
  "apt",
  "apt-get",
  "apk",
  "dnf",
  "yum",
  "zypper",
  "pacman",
  "brew",
  "port",
  "nix",
  "flatpak",
  "snap",
  "choco",
  "scoop",
  "winget",
]);

export const PACKAGE_SUBCOMMANDS: Record<string, Set<string>> = {
  npm: new Set([
    "install",
    "i",
    "add",
    "ci",
    "update",
    "upgrade",
    "run",
    "exec",
    "x",
  ]),
  pnpm: new Set(["install", "add", "update", "upgrade", "exec", "run", "dlx"]),
  yarn: new Set(["add", "install", "upgrade", "remove", "run", "exec"]),
  bun: new Set(["add", "install", "update", "upgrade", "remove", "run", "x"]),
  pip: new Set(["install", "download"]),
  pip3: new Set(["install", "download"]),
  poetry: new Set(["install", "add", "update", "upgrade"]),
  uv: new Set(["pip install", "add", "sync"]),
  pipx: new Set(["install", "inject", "upgrade"]),
  conda: new Set(["install", "create", "update"]),
  gem: new Set(["install", "update"]),
  bundle: new Set(["install", "update"]),
  cargo: new Set(["install", "add", "update", "fetch"]),
  go: new Set(["get", "install", "mod download", "mod tidy"]),
  composer: new Set(["install", "update", "require"]),
  apt: new Set(["install", "upgrade", "update", "remove", "purge"]),
  "apt-get": new Set(["install", "upgrade", "update", "remove", "purge"]),
  apk: new Set(["add", "upgrade", "del"]),
  dnf: new Set(["install", "upgrade", "remove"]),
  yum: new Set(["install", "upgrade", "remove"]),
  pacman: new Set(["-S", "-Sy", "-Syu", "-R", "-Rs"]),
  brew: new Set(["install", "upgrade", "reinstall"]),
};

export const NETWORK_CLIENTS = new Set([
  "curl",
  "wget",
  "nc",
  "ncat",
  "netcat",
  "socat",
  "ftp",
  "sftp",
  "scp",
  "rsync",
  "telnet",
  "dig",
  "nslookup",
  "host",
  "ping",
  "traceroute",
  "openssl",
  "httpie",
  "http",
  "aria2c",
  "axon",
]);

export const FILE_WRITE_TOOLS = new Set([
  "tee",
  "dd",
  "install",
  "truncate",
  "shred",
]);

export const FILE_MUTATION_TOOLS = new Set([
  "cp",
  "mv",
  "rename",
  "ln",
  "link",
  "symlink",
  "rsync",
]);

/** Options of the mutation tools that consume a separate value token, so the
 *  value is never mistaken for a source or destination operand. The lists
 *  cover structural options (destination and suffix selection). Options
 *  with optional values require an attached value and must not consume the
 *  following operand. */
export const MUTATION_VALUE_OPTIONS: Record<string, Set<string>> = {
  cp: new Set(["-t", "--target-directory", "-S", "--suffix"]),
  mv: new Set(["-t", "--target-directory", "-S", "--suffix"]),
  ln: new Set(["-t", "--target-directory", "-S", "--suffix"]),
  rsync: new Set([
    "--backup-dir",
    "-e",
    "--rsh",
    "--rsync-path",
    "--exclude-from",
    "--include-from",
    "--files-from",
    "--suffix",
    "--password-file",
    "--log-file",
    "--out-format",
  ]),
};

/** Executables with no observable side effects on the local filesystem when
 *  invoked with plain arguments. An executable NOT in this set (and in no
 *  effect family the analyzer checks) is classified "unknown", not read-only:
 *  the analyzer's inability to detect effects is not evidence that none
 *  exist. */
export const READ_ONLY_TOOLS = new Set([
  "cat",
  "less",
  "more",
  "ls",
  "head",
  "tail",
  "wc",
  "file",
  "stat",
  "pwd",
  "echo",
  "printf",
  "date",
  "whoami",
  "id",
  "uname",
  "hostname",
  "who",
  "w",
  "uptime",
  "which",
  "type",
  "printenv",
  "grep",
  "egrep",
  "fgrep",
  "rg",
  "find",
  "du",
  "df",
  "tree",
  "jq",
  "yq",
  "sort",
  "uniq",
  "cut",
  "column",
  "tr",
  "diff",
  "cmp",
  "comm",
  "md5sum",
  "sha1sum",
  "sha256sum",
  "sha512sum",
  "cksum",
  "base64",
  "xxd",
  "od",
  "strings",
  "nl",
  "tac",
  "rev",
  "fold",
  "fmt",
  "expand",
  "unexpand",
  "seq",
  "true",
  "false",
  "sleep",
  "clear",
  "test",
  "[",
  "basename",
  "dirname",
  "realpath",
  "readlink",
  "man",
  "info",
  "tput",
]);

/** Shell builtins with no filesystem side effects of their own (directory and
 *  environment manipulation only). */
export const NO_EFFECT_BUILTINS = new Set([
  "cd",
  "pushd",
  "popd",
  "dirs",
  "export",
  "unset",
  "set",
  "shopt",
  "alias",
  "unalias",
  "exit",
  "return",
  "shift",
  "wait",
  "jobs",
  "fg",
  "bg",
  "read",
  "local",
  "declare",
  "readonly",
  "getopts",
  "hash",
  "help",
  "let",
  "trap",
  "ulimit",
  "umask",
  "builtin",
  "command",
]);

export const DELETION_TOOLS = new Set([
  "rm",
  "rmdir",
  "unlink",
  "shred",
  "truncate",
]);

export const GIT_MUTATION_SUBCOMMANDS = new Set([
  "add",
  "am",
  "apply",
  "bisect",
  "branch",
  "checkout",
  "cherry-pick",
  "clean",
  "clone",
  "commit",
  "config",
  "fetch",
  "filter-branch",
  "gc",
  "init",
  "maintenance",
  "merge",
  "mv",
  "notes",
  "prune",
  "pull",
  "push",
  "rebase",
  "remote",
  "repack",
  "replace",
  "reset",
  "restore",
  "revert",
  "rm",
  "stash",
  "submodule",
  "switch",
  "symbolic-ref",
  "tag",
  "update-ref",
  "worktree",
]);

/** `git branch` options that make it list branches instead of changing one. */
export const BRANCH_LIST_OPTIONS: readonly string[] = [
  "-a",
  "--all",
  "-r",
  "--remotes",
  "-l",
  "--list",
  "-v",
  "-vv",
  "--show-current",
  "--contains",
  "--no-contains",
  "--merged",
  "--no-merged",
  "--points-at",
  "--format",
  "--sort",
  "--column",
];

/** `git tag` options that make it list tags instead of changing one. */
export const TAG_LIST_OPTIONS: readonly string[] = [
  "-l",
  "--list",
  "--contains",
  "--no-contains",
  "--merged",
  "--no-merged",
  "--points-at",
  "--format",
  "--sort",
  "--column",
];

/** `git config` options and subcommands that only read configuration. */
export const CONFIG_READ_OPTIONS: readonly string[] = [
  "--list",
  "-l",
  "--get",
  "--get-all",
  "--get-regexp",
  "--get-urlmatch",
  "--show-origin",
  "--show-scope",
  "get",
  "get-all",
  "get-regexp",
  "get-urlmatch",
  "list",
];

export const GIT_NETWORK_SUBCOMMANDS = new Set([
  "clone",
  "fetch",
  "ls-remote",
  "pull",
  "push",
]);

export const PRIVILEGE_WRAPPERS = new Set([
  "sudo",
  "doas",
  "pkexec",
  "su",
  "runuser",
  "super",
  "setpriv",
  "setcap",
  "capsh",
]);

export const SERVICE_MANAGERS = new Set([
  "systemctl",
  "service",
  "rc-service",
  "rc-update",
  "initctl",
  "launchctl",
  "supervisorctl",
  "pm2",
  "forever",
  "nodemon",
  "god",
  "circus",
]);

export const PERSISTENCE_WRAPPERS = new Set(["nohup", "setsid", "disown"]);
export const PERSISTENCE_TOOLS = new Set([
  "at",
  "atq",
  "atrm",
  "cron",
  "crontab",
]);

export const SSH_TOOLS = new Set(["ssh", "mosh", "autossh"]);

export const CREDENTIAL_READERS = new Set([
  "cat",
  "head",
  "tail",
  "less",
  "more",
  "grep",
  "rg",
  "sed",
  "awk",
  "base64",
  "xxd",
  "od",
  "strings",
  "source",
  ".",
]);
